### ISSUE TITLE
Create Application (User)

### ISSUE THREAD

**Issue by Dee-McG** [Dee-McG/Agile-Demo#2]
**User Story**

As a user, I would like to be able to create an application so that I can show how amazing I am and why I should be included on the mission to mars.

**Description**

Form needs to have the following fields:
* Qualifications (Image upload)
* Name (String)
* Age (Number)
* Proof id (Image upload)
* Address (String)

**Acceptance Criteria**

* Applications can only be made by logged in user
* A form is displayed on the create application page
* If all info is correct, form should sub successfully and toast message shown to user
* Is user inputs incorrect information, an error is displayed to the user

**Tasks**

- [ ] Create form on the application page
- [ ] Create model in the application app
- [ ] Add input validation in the forms.py
- [ ] Create the view to take the form input and store in the database
